### PR TITLE
add session tutorial code and scripts #8

### PR DESCRIPTION
**Pull request by ishiharatmy**
add baseline code and scripts of session tutorial #8 
please review it.

### CODE REVIEW

**Comment by ikeyat** [comment]
- [ ] follow https://github.com/terasolunaorg/tutorial-apps/issues/1#issuecomment-186801164

**Comment by ikeyat** [comment]
- [ ] Please add comments on shell scripts for complete that they generate complete project from init project.

**Comment by ikeyat** [comment]
- [ ] follow directory structure https://github.com/terasolunaorg/tutorial-apps/pull/11#issuecomment-186806124

**Comment by ishiharatmy** [comment]
- [ ]  I found that application did not pass an original test case from blank project because of authentication. I have fixed code and scripts. please review it.
https://github.com/terasolunaorg/tutorial-apps/commit/3f0d0396249a0083a198eb1d8e17524b67310175

**Pull request merged**
