### PR TITLE
todo original src initial import #1

### PR DESCRIPTION
**Pull request by btokadanob**
- [ ]  todo tutorial sources & generate scripts inital import.

----
issue: #1 

6d341b5a4f7338ba8a5f4954db0383d23758ccaa

21739441ffe9584fc764336f5466783031e9dc3c

----

### CODE REVIEW

**Comment by ikeyat** [comment]
- [ ] Please reconsider the structure of directories. Why don't you follow maven style structure?

**Comment by btokadanob** [comment]
- [ ] reconstructed direcorires 

---

issue #1 
2938f83df0cc5a2672f911638a5e68751531aa1b

---

**Comment by ikeyat** [comment]
- [ ] add .gitignore copied from terasoluna-gfw

**Comment by ikeyat** [comment]
- [ ] Are there any good points to put todo and todo-rest in a same directory ``todo`` ? If there is no merits they should be put into different directories to make it easy to maintain separately.

**Comment by kazuki43zoo** [comment]
- [ ] I want to add documents of this repository for maintain. (directory structures, how to use, etc..)

**Comment by btokadanob** [comment]
- [x] todo & todo-rest & first-spring-security.  its root dir for each app 

---

issue #1 
69f3687b5447ef5dacfa398b1e9c94e4be35453c

I understood. will make the document for maintenance in other rep.

---

**Comment by ikeyat** [comment]
OK

**Pull request merged**
